# Generated by Django 3.0.4 on 2020-03-24 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userID', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('bio', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=30)),
                ('pictureURL', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Carts',
            fields=[
                ('userID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='homepage.Users')),
                ('recipeIDs', models.CharField(max_length=1000)),
                ('dateUpdated', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='UserFavorites',
            fields=[
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='homepage.Users')),
                ('recipeID', models.CharField(max_length=50)),
            ],
            options={
                'unique_together': {('userID', 'recipeID')},
            },
        ),
        migrations.CreateModel(
            name='OwnsRecipes',
            fields=[
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='homepage.Users')),
                ('recipeID', models.CharField(max_length=50)),
            ],
            options={
                'unique_together': {('userID', 'recipeID')},
            },
        ),
    ]
